services:
  postgres:
    image: postgres:16-alpine
    container_name: sales-backend-db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_sales:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data_sales: